### ISSUE TITLE
Update proposal with some of my stuff

### ISSUE THREAD

**Issue by goldmojo** [SeongGino/RetroGame350-AppRepo#2]
Hello,

I propose the attached update (I didn't want to fork the entire repo in order to pull request).

I includes 3 of my recent repo :
* Atomiks (Atomix clone)
* OpenDune (Dune 2 clone)
* UnrealSpeccyP (ZX Spectrum emulator)

File format should be ok : 
[README.zip](https://github.com/SeongGino/RetroGame350-AppRepo/files/5179708/README.zip)

**Comment by SeongGino** [comment]
Apologies for the delay.
This has been addressed as of c2230ac.

Closing...
